# Configuration file for TreasureHunt
# Created by KevinNovak

huntItem: FILLED_MAP

huntArea:
  world: 'world'
  x-Range:
    min: -500
    max: 500
  y-Range:
    min: 4
    max: 50
  z-Range:
    min: -500
    max: 500

spawnInterval: 1800
chestDuration: 10800
openedChestDuration: 3600
announceTime:
  enabled: true
  atRemainingTimes:
    - 600
    - 300
    - 60
closestPlayer:
  enabled: true
  interval: 5

minPlayersOnline: 3
maxChests: 5

maxSpawnAttempts: 3000
maxFitItemAttempts: 3

defaultItemWeight: 100

bufferPercentage: 10

spawnUnder:
  air: true
  water: false
  lava: false

dontSpawnOn:
  - ACACIA_BUTTON
  - ACACIA_SAPLING
  - ALLIUM
  - AZURE_BLUET
  - BIRCH_BUTTON
  - BIRCH_SAPLING
  - BLUE_ORCHID
  - BROWN_MUSHROOM
  - CARROTS
  - CHEST
  - COCOA
  - DANDELION
  - DANDELION_YELLOW
  - DARK_OAK_BUTTON
  - DARK_OAK_SAPLING
  - DEAD_BUSH
  - FERN
  - FIRE
  - GRASS
  - JUNGLE_BUTTON
  - JUNGLE_SAPLING
  - LADDER
  - LARGE_FERN
  - LAVA
  - LEVER
  - LILAC
  - NETHER_WART_BLOCK
  - OAK_BUTTON
  - OAK_SAPLING
  - ORANGE_TULIP
  - OXEYE_DAISY
  - PEONY
  - PINK_TULIP
  - POPPY
  - POTATOES
  - REDSTONE_TORCH
  - REDSTONE_WALL_TORCH
  - REDSTONE_WIRE
  - RED_MUSHROOM
  - RED_TULIP
  - ROSE_BUSH
  - SIGN
  - SPRUCE_BUTTON
  - SPRUCE_SAPLING
  - STONE_BUTTON
  - SUGAR_CANE
  - SUNFLOWER
  - TALL_GRASS
  - TALL_SEAGRASS
  - TORCH
  - TRAPPED_CHEST
  - VINE
  - WALL_SIGN
  - WALL_TORCH
  - WATER
  - WHEAT
  - WHITE_TULIP

protectAgainst:
  break: true
  burn: true
  explode: true

notifyAdminsOnChestSpawnFail: true