name: TreasureHunt
version: '${project.version}'
main: me.kevinnovak.treasurehunt.TreasureHunt
api-version: '1.16'
authors: [KevinNovak]
description: Hunt for treasure!

commands:
  th:
    usage: /<command>
    description: List all TreasureHunt commands.
    aliases: [treasurehunt]

permissions:
  treasurehunt.item:
    description: Use the treasure hunt item.
    default: true
  treasurehunt.command.help:
    description: View treasure hunt help.
    default: true
  treasurehunt.command.list:
    description: Show available treasure chests.
    default: true
  treasurehunt.command.top:
    description: Show top treasure hunters.
    default: true
  treasurehunt.command.start:
    description: Start a treasure hunt.
    default: op
  treasurehunt.command.despawn:
    description: Despawn all treasure chests.
    default: op
